# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=10)),
                ('u_name', models.CharField(max_length=100)),
                ('u_gender', models.CharField(max_length=1)),
                ('u_mob', models.IntegerField(max_length=10)),
                ('u_email', models.CharField(max_length=100)),
                ('u_perm', models.CharField(max_length=32)),
            ],
        ),
    ]
