# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0003_auto_20181122_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('d_id', models.IntegerField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=32)),
                ('d_state', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='User_Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_manager.Device')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_manager.User')),
            ],
        ),
    ]
